- name: Debug zsh_user_config_dir
  debug:
    var: zsh_user_config_dir

- name: Ensure .config directory exists
  file:
    path: '{{ zsh_user_config_dir }}'
    state: directory
    owner: '{{ zsh_user }}'
    group: '{{ zsh_user }}'
    mode: '0755'
  become: true
  # become_user: "{{ zsh_user }}"

- name: Gather package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Check packages
  debug:
    var: ansible_facts.packages

- name: Copy zsh tool configs
  include_tasks: copy-config.yml
  loop: '{{ zsh_packages }}'
  loop_control:
    label: '{{ item }}'
# - name: Copy application files
#   copy:
#     src: files/config/          # relative to your playbook (or role’s files/)
#     dest: "{{ zsh_user_config_dir }}/"          # will create /etc/myapp/…
#     owner: "{{ zsh_user }}"
#     group: "{{ zsh_user }}"
#     mode: '0755'
#     force: no
# become: true
# - name: Ensure each export KEY=VALUE is present (replace or add)
#   lineinfile:
#     path: "{{ zsh_user_home }}/.aliases"
#     create: no              # we already touched above
#     regexp: '^export {{ item.key }}='
#     line: 'export {{ item.key }}={{ item.value }}'
#     backrefs: no
#   loop: "{{ bash_aliases_exports | dict2items }}"
#   loop_control:
#     label: "{{ item.key }}"
