# roles/main_user_zsh/tasks/install.yml

- name: Ensure apt cache is updated
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: true
  when: ansible_facts['pkg_mgr'] == 'apt'

- name: Install packages via apt
  apt:
    name: "{{ zsh_packages }}"
    state: present
    install_recommends: no
  become: true
  when: ansible_facts['pkg_mgr'] == 'apt'

- name: Install packages via homebrew
  homebrew:
    name: "{{ zsh_packages }}"
    state: present
    update_homebrew: yes
  become: true
  when: ansible_facts['pkg_mgr'] == 'homebrew'
